#
# Dizici
# https://github.com/Ardakilic/dizici
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @link        https://github.com/Ardakilic/dizici
# @copyright   2016 Arda Kilicdagi. (https://arda.pw/)
# @license     http://opensource.org/licenses/MIT - MIT License
#

timezone: Europe/Istanbul
connection:
  driver: sqlite
  database: dizici.sqlite
  prefix: ''