#!/usr/bin/env php
<?php

/**
 * Dizici
 * https://github.com/Ardakilic/dizici
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @link        https://github.com/Ardakilic/dizici
 * @copyright   2016 Arda Kilicdagi. (https://arda.pw/)
 * @license     http://opensource.org/licenses/MIT - MIT License
 */

require_once __DIR__ . '/bootstrap.php';

use Symfony\Component\Console\Application;

use App\Commands\MigrateCommand;
use App\Commands\SyncSeriesCommand;

$application = new Application("Fetcher", APP_VERSION);

//Custom commands
$application->add(new MigrateCommand());
$application->add(new SyncSeriesCommand());

//Run it
$application->run();